#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 366620338322-haoa7c57ri2pbm0ljh95onf7dj98glq7.apps.googleusercontent.com
#            client-secret: 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
#          facebook:
#            client-id: testing
#            client-secret: testing123
#          github:
#            client-id: testing
#            client-secret: testing123
#
#
#
